name: Golang script
author: Ofadiman
description: Run golang script.

branding:
  color: purple
  icon: globe

inputs:
  script:
    description: Golang script name
    required: true
  go_version:
    description: Golang version
    required: false
    default: 1.20.2

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go_version }}

    - name: Go version
      shell: bash
      run: go version

    - name: Debug files
      shell: bash
      run: |
        ls -lrt
        ls -lrt scripts/

    - name: Run script
      shell: bash
      run: go run ${{ inputs.script }}
