name: Golang script
author: Ofadiman
description: Run golang script.

branding:
  color: purple
  icon: globe

inputs:
  script:
    description: Golang script name
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: stable

    - name: Run script
      shell: bash
      run: go run ${{ github.action_path }}/${{ inputs.script }}
