name: Custom action tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Run golang script
        id: golang_script
        uses: Ofadiman/golang-script@main
        with:
          script: scripts/main.go

      - name: Log golang script output
        run: |
          echo "output was: ${{ steps.golang_script.outputs.value }}"
