name: Deno

on:
  workflow_dispatch:
    inputs:
      message:
        description: Message to log
        required: true
        default: Hello world

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Setup deno
        uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: 1.31.1

      - name: Run script
        id: golang_script
        run: deno run --allow-env --allow-read --allow-write .github/scripts/deno.ts --message "${{ inputs.message }}" --foo bar

      - name: Log golang script output
        run: |
          echo "output was: ${{ steps.golang_script.outputs.value }}"
