name: Golang

on:
  workflow_dispatch:
    inputs:
      message:
        description: Message to log
        required: true
        default: Hello world

jobs:
  main:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Setup golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Run script
        id: script
        run: go run .github/scripts/golang.go -message "${{ inputs.message }}"

      - name: Script output
        run: |
          echo "script output: ${{ steps.script.outputs.value }}"
