name: Golang script tests

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Run golang script
        uses: Ofadiman/golang-script@v1.0.2
        with:
          script: scripts/main.go
