name: Golang script tests

on:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.2

      - name: Go version
        run: go version

      - name: Debug files
        run: |
          ls -lrt
          ls -lrt scripts/

      - name: Run script
        run: go run scripts/main.go
